---
language: node_js
node_js:
  - "10"

sudo: false

cache:
  yarn: true
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=2.13.3
  - EMBER_TRY_SCENARIO=2.16.2
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary

dist: xenial

addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver

before_script:
  - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - npm install -g bower
  - npm install -g yarn
  - yarn install
  - bower install

script:
  - ember try:each
